version: '3.7'
services:
#portainer
 portainer:
  image: portainer/portainer-ce
  container_name: portainer
  restart: unless-stopped
  security_opt:
   - no-new-privileges:true
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /var/run/docker.sock:/var/run/docker.sock:ro
   - ./portainer-data:/data
  ports:
   - 9100:9000
#sonarqube
 sonarqube:
  image: sonarqube:8.2-community
  restart: unless-stopped
  depends_on:
   - db
  ports:
   - 9000:9000
  networks:
   - sonarnet
  environment:
   POSTGRES_USER: sonar
   POSTGRES_PASSWORD: sonar
  volumes:
   - sonarqube_data:/opt/sonarqube/data
   - sonarqube_extensions:/opt/sonarqube/extensions
   - sonarqube_logs:/opt/sonarqube/logs
   - sonarqube_temp:/opt/sonarqube/temp
 db:
  image: postgres
  networks:
   - sonarnet
  environment:
   POSTGRES_USER: sonar
   POSTGRES_PASSWORD: sonar
  volumes:
   - postgresql:/var/lib/postgresql
   - postgresql_data:/var/lib/postgresql/data
#networks
networks:
 sonarnet:
  driver: bridge
volumes:
 sonarqube_data:
 sonarqube_extensions:
 sonarqube_logs:
 sonarqube_temp:
 postgresql:
 postgresql_data:
#docker run -d -p 8081:8081 --name nexus --restart=always -v nexus-data:/nexus-data sonatype/nexus3:3.33.1
